settings:
  commit_msg: Updated recent activity
  max_lines: 7
  commit_name: GitHub Actions
  commit_email: 41898282+github-actions[bot]@users.noreply.github.com
  date:
    timezone: Europe/Moscow

messages:
  comments: '<img src=".github/icons/Comment.svg"> Commented on {ID} in {REPO}'
  issue_opened: '<img src=".github/icons/IssueOpened.svg"> Opened issue {ID} in {REPO}'
  issue_closed: '<img src=".github/icons/IssueClosed.svg"> Closed issue {ID} in {REPO}'
  pr_opened: '<img src=".github/icons/PullRequestOpened.svg"> Opened PR {ID} in {REPO}'
  pr_closed: '<img src=".github/icons/PullRequestClosed.svg"> Closed PR {ID} in {REPO}'
  pr_merged: '<img src=".github/icons/PullRequestMerged.svg"> Merged PR {ID} in {REPO}'
  create_repo: '<img src=".github/icons/RepositoryCreated.svg"> Created new repository {REPO}'
  fork_repo: '<img src=".github/icons/ForkedRepository.svg"> Forked {FORK} from {REPO}'
  wiki_create: '<img src=".github/icons/Wiki.svg"> Created new wiki page {WIKI} in {REPO}'
  added_member: '<img src=".github/icons/People.svg"> Became collaborator on {REPO}'
  changes_approved: '<img src=".github/icons/ApprovedChanges.svg"> Approved {ID} in {REPO}'
  changes_requested: '<img src=".github/icons/RequestedChanges.svg"> Requested changes in {ID} in {REPO}'
  new_release: '<img src=".github/icons/Release.svg"> Released {ID} in {REPO}'
  new_star: '<img src=".github/icons/StarredRepository.svg"> Starred {REPO}'