name: Daily update

on:
  schedule:
    - cron: '40 3 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_KEY }}

      # - name: Download Readme Activity Graph
      #   run: |
      #     mkdir static_assets
      #     cd static_assets
      #     wget -O "activity-graph.svg" "https://npanuhin-activity-graph.herokuapp.com/graph?username=npanuhin&theme=react-dark&bg_color=transparent&point=00ff12&hide_border=true&area=true&custom_title=GitHub%20contributions"

      # - name: Push static assets
      #   uses: crazy-max/ghaction-github-pages@v2.5.0
      #   with:
      #     target_branch: output
      #     build_dir: static_assets
      #     commit_message: Updated static assets
      #     allow_empty_commit: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT }}


      # - name: Update metrics
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.svg
      #     token: ${{ secrets.PAT }}
      #     # committer_token: ${{ secrets.GITHUB_TOKEN }}
      #     config_timezone: Europe/Moscow
      #     base:

      #     committer_message: Updated metrics

      #     # plugin_introduction: yes
      #     # plugin_introduction_title: yes
      #     # plugin_lines: yes
      #     # plugin_music: no
      #     # plugin_isocalendar: yes
      #     # plugin_isocalendar_duration: full-year
      #     # plugin_topics: yes
      #     # plugin_topics_sort: random
      #     # plugin_habits: yes
      #     # plugin_habits_from: 200
      #     # plugin_habits_facts: yes
      #     # plugin_habits_charts: yes
      #     # plugin_stars: yes
      #     # plugin_stars_limit: 4
      #     # plugin_stargazers: yes
      #     # plugin_activity: yes
      #     # plugin_activity_limit: 5
      #     # plugin_activity_days: 14
      #     # plugin_people: yes
      #     # plugin_people_types: followers, following
      #     # plugin_people_limit: 200
      #     # plugin_people_size: 28
      #     # plugin_tweets: yes
      #     # plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
      #     # repositories_forks: yes
      #     # plugin_skyline: yes
      #     # plugin_skyline_year: 2020
      #     # plugin_skyline_frames: 120
      #     # plugin_skyline_quality: 1
      #     # plugin_skyline_compatibility: no
      #     # plugin_reactions: yes
      #     # plugin_reactions_limit: 200
      #     # plugin_reactions_days: 14
      #     # plugin_reactions_details: percentage
      #     # plugin_achievements: yes
      #     # plugin_achievements_threshold: C       
      #     # plugin_achievements_secrets: yes   
      #     # plugin_achievements_limit: 0
      #     # plugin_achievements_display: compact   
      #     # plugin_notable: yes
      #     # plugin_tweets_attachments: yes
      #     # plugin_support: yes

      #     # plugin_gists: yes
