settings:
  max_lines: 7
  commit_msg: Updated recent activity
  commit_name: GitHub Actions
  commit_email: 41898282+github-actions[bot]@users.noreply.github.com

  username: npanuhin

messages:
  comment: '<img src=".github/icons/Comment.svg"> Commented on {ID} in {REPO}'
  repo_created: '<img src=".github/icons/RepositoryCreated.svg"> Created new repository {REPO}'
  repo_forked: '<img src=".github/icons/ForkedRepository.svg"> Forked {FORK} from {REPO}'
  wiki_created: '<img src=".github/icons/Wiki.svg"> Created new wiki page {WIKI} in {REPO}'
  issue_opened: '<img src=".github/icons/IssueOpened.svg"> Opened issue {ID} in {REPO}'
  issue_reopened: '<img src=".github/icons/IssueOpened.svg"> Reopened issue {ID} in {REPO}'
  issue_closed: '<img src=".github/icons/IssueClosed.svg"> Closed issue {ID} in {REPO}'
  pr_opened: '<img src=".github/icons/PullRequestOpened.svg"> Opened PR {ID} in {REPO}'
  pr_reopened: '<img src=".github/icons/PullRequestOpened.svg"> Reopened PR {ID} in {REPO}'
  pr_closed: '<img src=".github/icons/PullRequestClosed.svg"> Closed PR {ID} in {REPO}'
  pr_merged: '<img src=".github/icons/PullRequestMerged.svg"> Merged PR {ID} in {REPO}'
  # collaboration: '<img src=".github/icons/People.svg"> Added {ID} as a collaborator in {REPO}'
  changes_approved: '<img src=".github/icons/ApprovedChanges.svg"> Approved {ID} in {REPO}'
  changes_requested: '<img src=".github/icons/RequestedChanges.svg"> Requested changes in {ID} in {REPO}'
  released: '<img src=".github/icons/Release.svg"> Released {ID} in {REPO}'
  starred: '<img src=".github/icons/StarredRepository.svg"> Starred {REPO}'
