name: GitHub Language Bar

on:
  push:                     # Run every time config or README changes
    paths:
      - '/README.md'
      - '/.github/workflows/language_bar.yml'
  schedule:                 # Run every day close to 00:00
    - cron: '50 23 * * *'
  workflow_dispatch:        # Run with a button in the Actions tab

jobs:
  language_bar:
    name: Create GitHub Language Bar
    runs-on: ubuntu-latest
    steps:
      - name: Create Language Bar
        uses: npanuhin/GitHub-Language-Bar@master
        with:
          gh_token: ${{ secrets.LANG_BAR_PAT }}
